<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>21f51680-292b-4b27-9e2b-4c0900373c32</testSuiteGuid>
   <testCaseLink>
      <guid>c58a7ea5-03ed-465f-b446-d76a76ccb40d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional Testing/TC-01 Login/TC-01-01 Login Success</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>63e7cd93-3e23-4436-90dd-bce4f03c4928</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/KatalonData/ValidLogin</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>63e7cd93-3e23-4436-90dd-bce4f03c4928</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>42646375-6bc9-4a1b-9334-aff1c3125326</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>63e7cd93-3e23-4436-90dd-bce4f03c4928</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>ec9204d6-1bcd-461a-ae50-080eab3f55cc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>659acb48-dbe2-4b43-87ad-248e2994e655</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional Testing/TC-01 Login/TC-01-02 Failed login with invalid username</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5c338b82-5527-48f0-8ecc-1f44aaf2a891</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/KatalonData/InvalidUsername</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>5c338b82-5527-48f0-8ecc-1f44aaf2a891</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>5a8c951f-7e7a-45ff-878c-7b390db7319c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5c338b82-5527-48f0-8ecc-1f44aaf2a891</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>c57c0191-8185-4c3f-9cb8-424e34cb652b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1abd4a2b-f28d-4511-abba-2eb0930eb160</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional Testing/TC-01 Login/TC-01-03 Failed login with invalid password</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>26b7d0fa-a31b-44ef-96be-e9a5dad58255</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/KatalonData/InvalidPassword</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>26b7d0fa-a31b-44ef-96be-e9a5dad58255</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>3003adbb-d195-4ea0-877c-71c969682401</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>26b7d0fa-a31b-44ef-96be-e9a5dad58255</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>d5286b54-a737-423b-91e0-2ea47875d943</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>69ea39d3-e9a9-4b29-a061-022bd2436848</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional Testing/TC-01 Login/TC-01-04 Failed login with empty username</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>efc74d9c-3cc8-44fb-b874-768f1533fd88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>225c06fe-4971-4967-80ba-56d567554e8a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ca324deb-24f1-444a-9605-6351375c40e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional Testing/TC-01 Login/TC-01-05 Failed login with empty password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02ae93e8-457e-41be-8179-0d99167260f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9f184f4-55cd-4114-b65c-e914cdcb717e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5dc2d562-50d1-402c-a0da-0e30e634568b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional Testing/TC-01 Login/TC-01-06 Failed login with empty username and password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6917ac14-1d6b-4e7b-9230-2f0eb48b17e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e969a7ae-cee0-4d3b-aac3-cc756259e9c5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
